
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxctnuzbrjywpxeoeoef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4Y3RudXpicmp5d3B4ZW9lb2VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDM0NzIsImV4cCI6MjA1OTUxOTQ3Mn0.7rUDoXiIiMHRQ2cRnadkm79DnTwXJN2FZVoQRZbEwy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
